# Generated by Django 5.0.7 on 2026-07-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='0000000000', help_text='Enter phone number (e.g., 10 digits or with country code)', max_length=15, unique=True, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
